# Generated by Django 3.1.6 on 2021-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('date_login', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_login'],
            },
        ),
    ]
